services:
  # --- Infraestrutura ---
  rabbitmq:
    image: rabbitmq:3-management
    container_name: weather-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
        test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
        interval: 10s
        timeout: 5s
        retries: 5

  mongodb:
    image: mongo
    container_name: weather-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: weather-mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb

  # --- Aplicações ---
  
  # 1. API Backend (NestJS)
  api:
    build: ./weather-api
    container_name: weather-api
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/weather
      JWT_SECRET: segredo_super_secreto_do_desafio
    depends_on:
      - mongodb

  # 2. Worker (Go)
  worker:
    build: ./weather-worker
    container_name: weather-worker
    environment:
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672/
    depends_on:
      rabbitmq:
        condition: service_healthy
      api:
        condition: service_started

  # 3. Collector (Python)
  collector:
    build: ./weather-collector
    container_name: weather-collector
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: user
      RABBITMQ_PASS: password
      QUEUE_NAME: weather_data
      LATITUDE: -25.52
      LONGITUDE: -48.51
    depends_on:
      rabbitmq:
        condition: service_healthy

  # 4. Frontend (React)
  frontend:
    build: ./weather-frontend
    container_name: weather-frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3000
    depends_on:
      - api

volumes:
  mongo-data: